// Har category ke liye jaani-pehchani providers ki list - Add Payment screen par
// category select karne ke baad ek dropdown mein dikhti hain. Provider choose
// karne se sirf "Title" field bhar jati hai, koi naya data field nahi chahiye.
export const PROVIDERS = {
  rent: [
    "Zillow Rental Manager",
    "Apartments.com",
    "RentCafe",
    "AppFolio",
    "Buildium",
    "Private Landlord",
  ],
  car: [
    "Toyota Financial Services",
    "Ally Financial",
    "Capital One Auto Finance",
    "Chase Auto",
    "Honda Financial Services",
    "Ford Credit",
    "GM Financial",
    "Wells Fargo Auto",
  ],
  insurance: [
    "Geico",
    "Progressive",
    "State Farm",
    "Allstate",
    "Liberty Mutual",
    "USAA",
    "Farmers",
    "Nationwide",
  ],
  subscription: [
    "Netflix",
    "Spotify",
    "Disney+",
    "Amazon Prime",
    "Hulu",
    "HBO Max",
    "YouTube Premium",
    "Apple Music",
    "Apple TV+",
  ],
  bills: [
    "National Grid",
    "Eversource",
    "Liberty Utilities",
    "Duke Energy",
    "Con Edison",
    "PG&E",
    "Southern California Edison",
    "Xcel Energy",
    "Dominion Energy",
    "PSE&G",
    "American Electric Power",
    "Georgia Power",
    "Florida Power & Light",
    "CenterPoint Energy",
    "Ameren",
    "We Energies",
    "Puget Sound Energy",
    "Atmos Energy",
    "Southwest Gas",
    "Verizon",
    "AT&T",
    "T-Mobile",
    "Boost Mobile",
    "Cricket Wireless",
    "Metro by T-Mobile",
    "Mint Mobile",
    "Visible",
    "US Cellular",
    "Google Fi",
    "Xfinity Mobile",
    "Spectrum Mobile",
    "Straight Talk",
    "Consumer Cellular",
    "Other Provider",
  ],
  other: [],
};
